# Generated by Django 5.1.2 on 2024-10-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='salary',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
